name: opa-agent
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: rm -rf GitVersion.yml README.md .gitignore .vscode .github

      - name: upload artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist
          path: ./

  deploy_stg_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: stg
    name: deploy stg westeurope
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist"
          path: ./

      - name: az login
        uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: deploy
        uses: Azure/functions-action@v1.3.2
        with:
          package: ./
          app-name: func-${{ github.workflow }}-westeurope-stg

  # deploy_stg_westus2:
  #   if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   environment: stg
  #   name: deploy stg westus2
  #   steps:
  #     - name: download artifact
  #       uses: actions/download-artifact@v2.0.10
  #       with:
  #         name: "dist"
  #         path: ./dist

  #     - name: az login
  #       uses: Azure/login@v1
  #       with:
  #         creds: |
  #           {
  #             "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
  #             "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
  #             "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
  #             "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
  #           }

  #     - name: deploy
  #       uses: Azure/functions-action@v1.3.2
  #       with:
  #         package: ./dist
  #         app-name: func-${{ github.workflow }}-westus2-stg

  deploy_prod_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    name: deploy prod westeurope
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist"
          path: ./dist

      - name: az login
        uses: Azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: deploy
        uses: Azure/functions-action@v1.3.2
        with:
          package: ./dist
          app-name: func-${{ github.workflow }}-westeurope-prod
